jsettlers.graphics/src/jsettlers/graphics/map/draw/Background.java

@michaelzangl: Do you see any issues with this fix? Or do you think it is ok?

Fixed NullPointerException in Background.java (fixes #13).

---

jsettlers.graphics/src/jsettlers/graphics/map/controls/original/panel/content/BuildingButton.java
jsettlers.graphics/src/jsettlers/graphics/map/draw/ImageProvider.java
jsettlers.graphics/src/jsettlers/graphics/utils/UIPanel.java

The building images now use higher resolution versions when there
are enough pixels available for the image to be drawn in (larger
screen size).
This also applies for other icons in the control panel.

Enabled responsive image resolution for building panel images.

---

jsettlers.common/resources/localization/labels_en.properties
jsettlers.graphics/src/jsettlers/graphics/localization/Labels.java

Fixed the default language to en if user language file is missed.
Fixed 2 small type errors in english locale file.

Fixed small locales error

---

jsettlers.common/resources/localization/labels_ru.properties

added and translated the missing Russian locale string

new lines translated into Russian

---

jsettlers.common/resources/buildings/goldmine.xml

It was clear: while checking the mines pull request I just checked coal and iron mine. ... However the goldmine produces coal at the moment.
Sorry!
This pull request is the bugfix for that.

bugfix: goldmine produces goldore instead of coal

---

jsettlers.common/src/jsettlers/common/buildings/EBuildingType.java
jsettlers.logic/src/jsettlers/ai/construction/BestLumberJackConstructionPositionFinder.java
jsettlers.logic/src/jsettlers/ai/construction/BestMilitaryConstructionPositionFinder.java
jsettlers.logic/src/jsettlers/ai/construction/BestStoneCutterConstructionPositionFinder.java
jsettlers.logic/src/jsettlers/ai/construction/BestWaterWorksConstructionPositionFinder.java
jsettlers.logic/src/jsettlers/ai/construction/BestWorkareaConstructionPositionFinder.java
jsettlers.logic/src/jsettlers/ai/highlevel/AiExecutor.java
jsettlers.logic/src/jsettlers/ai/highlevel/AiPositions.java
jsettlers.logic/src/jsettlers/ai/highlevel/AiStatistics.java
jsettlers.logic/src/jsettlers/ai/highlevel/RomanWhatToDoAi.java
jsettlers.logic/src/jsettlers/logic/map/grid/MainGrid.java
jsettlers.logic/src/jsettlers/logic/map/grid/landscape/LandscapeGrid.java

* Added AiPositions to as set of ShortPoint2D that allows faster close point search.
* Use that AiPositions everywhere a list is used.
* Reduce the usage of Hashsets
* Make methods static.
* split updateMapStatistics() into multiple methods.

Feature computerplayer faster

---

jsettlers.common/resources/localization/labels_en.properties

A little map I made consisting of 3 interconnected craters, surrounded by impassible snowy mountains.
Also an excellent demonstration of #215.

Map Settler Craters

---

jsettlers.common/src/jsettlers/common/CommonConstants.java
jsettlers.logic/src/jsettlers/logic/map/original/OriginalMapFileContentReader.java
jsettlers.logic/src/jsettlers/logic/map/original/OriginalMapLoader.java
jsettlers.logic/src/jsettlers/logic/map/save/MapList.java
jsettlers.main.swing/options.prp

- read and return map preview from original map file
- disable checksum validation cause of speed problems:
=> Add "disable-original-maps-checksum = true" to options.prp
- bugfixes
Example of original-maps displaying within new GUI from andreasb242/codingberlin :
PS: your new GUI looks quite good :-)

OriginalMap: add map preview

---

jsettlers.logic/src/jsettlers/ai/highlevel/AiStatistics.java

fixes #266: AI does not destroy towers next to other player's land

---

jsettlers.common/resources/localization/labels_de.properties
jsettlers.common/resources/localization/labels_en.properties
jsettlers.common/resources/localization/labels_pl.properties

Fixed some typos and added some missing label strings.

Localization tiny fixes.

---

jsettlers.common/src/jsettlers/common/crash/ConsoleCrashHandler.java
jsettlers.common/src/jsettlers/common/crash/CrashHandler.java
jsettlers.common/src/jsettlers/common/crash/CrashReportQueue.java
jsettlers.common/src/jsettlers/common/crash/CrashReportSettings.java
jsettlers.common/src/jsettlers/common/crash/CrashReportedException.java
jsettlers.common/src/jsettlers/common/crash/CrashReporting.java
jsettlers.graphics/src/jsettlers/graphics/map/MapContent.java
jsettlers.graphics/src/jsettlers/graphics/map/draw/MapObjectDrawer.java
jsettlers.main.swing/src/jsettlers/main/swing/SwingManagedJSettlers.java

A new framework to create and handle crash reports. Allows the addition of a nice GUI for this.

Bugreporter

---

jsettlers.logic/src/main/java/jsettlers/ai/construction/BestFarmConstructionPositionFinder.java
jsettlers.logic/src/main/java/jsettlers/ai/construction/BestPlantingBuildingConstructionPositionFinder.java
jsettlers.logic/src/main/java/jsettlers/ai/construction/BestWinegrowerConstructionPositionFinder.java
jsettlers.logic/src/main/java/jsettlers/ai/highlevel/AiStatistics.java

- fix ArrayOutOfBoundsException when farm or winegrower should be build next to the map border by AI
- merged code of BestFarmConstructionPositionFinder and BestWineGrowerConstructionPositionFinder to DRY
- fix ArrayOutOfBoundsException when Lumberjack should be build next to the map border by AI
- fix NullPointerException when tower should be build by AI but no default partition exists

3 AI exception fixes

---

jsettlers.graphics/src/main/resources/jsettlers/graphics/localization/labels_de.properties
jsettlers.graphics/src/main/resources/jsettlers/graphics/localization/labels_en.properties

Added some more cannot work message localizations for de and en.

---

jsettlers.logic/src/main/java/jsettlers/input/GuiInterface.java

Fixed double counting of directly selected movable when doing a selection by movable type.

---

jsettlers.logic/src/main/java/jsettlers/logic/map/grid/partition/PartitionsListingBorderVisitor.java

Fixed partitions not being divided by pioneers if their north east position was blocked.

---

jsettlers.logic/src/main/java/jsettlers/ai/construction/BestFisherConstructionPositionFinder.java
jsettlers.logic/src/main/java/jsettlers/ai/construction/BestWaterWorksConstructionPositionFinder.java
jsettlers.logic/src/main/java/jsettlers/ai/highlevel/AiPositions.java
jsettlers.logic/src/main/java/jsettlers/ai/highlevel/AiStatistics.java
jsettlers.logic/src/main/java/jsettlers/ai/highlevel/WhatToDoAi.java

Improving AI performance by reducing used search radius when calling AiPositions.getNearestPoint()

---

jsettlers.common/src/main/java/jsettlers/common/CommonConstants.java

As my old server contract was canceled by the provider, I switched to a new instance with the new IP.

Updated multiplayer server ip to new instance.

---

jsettlers.common/src/main/java/jsettlers/common/buildings/jobs/EBuildingJobType.java

Fix javadoc for building job type

---

build.gradle
settings.gradle

Disable Android if the user did not set the android sdk.

---

jsettlers.main.android/AndroidManifest.xml
jsettlers.main.android/build.gradle
jsettlers.main.android/src/main/java/jsettlers/main/android/JsettlersActivity.java
jsettlers.main.android/src/main/java/jsettlers/main/android/resources/scanner/FileChoserFragment.java
jsettlers.main.android/src/main/res/values-de/strings.xml
jsettlers.main.android/src/main/res/values/strings.xml
jsettlers.main.android/src/main/res/values/styles.xml

Adding Android 6 runtime permission checks

---

jsettlers.graphics/src/main/resources/jsettlers/graphics/localization/labels_de.properties

Add missing german localizations.

---

go.graphics.android/src/main/java/go/graphics/android/AndroidTextDrawer.java
go.graphics.swing/src/main/java/go/graphics/swing/text/JOGLTextDrawer.java
go.graphics/src/main/java/go/graphics/text/TextDrawer.java
jsettlers.graphics/src/main/java/jsettlers/graphics/action/ActionFirerer.java
jsettlers.graphics/src/main/java/jsettlers/graphics/action/ActionThreadBlockingListener.java
jsettlers.graphics/src/main/java/jsettlers/graphics/font/FontDrawer.java
jsettlers.graphics/src/main/java/jsettlers/graphics/map/ETextDrawPosition.java
jsettlers.graphics/src/main/java/jsettlers/graphics/map/MapContent.java
jsettlers.main.android/src/main/java/jsettlers/main/android/JsettlersActivity.java
jsettlers.main.swing/src/main/java/jsettlers/main/swing/JSettlersFrame.java
jsettlers.mapcreator/src/main/java/jsettlers/mapcreator/control/EditorControl.java

This is required for the new Android UI build in PR #532. There texts need to be displayed on the left side, instead of the right side.

Make the text position of fps, game time and commit hash configurable

---

go.graphics.swing/src/main/java/go/graphics/swing/sound/SwingSoundPlayer.java
jsettlers.graphics/src/main/java/jsettlers/graphics/map/MapContent.java
jsettlers.graphics/src/main/java/jsettlers/graphics/map/draw/MapObjectDrawer.java
jsettlers.graphics/src/main/java/jsettlers/graphics/sound/BackgroundSound.java
jsettlers.graphics/src/main/java/jsettlers/graphics/sound/SoundManager.java

object sound improved: carpenter, falling tree, etc
region sound improved: mountain, river, desert, etc.
position dependent sound
zoom dependent sound

Make audio position dependend and fix some sounds

---

jsettlers.graphics/src/main/java/jsettlers/graphics/sound/SoundManager.java

change ">" and "<" in playSound

play sound when visible

---

jsettlers.logic/src/main/java/jsettlers/logic/map/grid/MainGrid.java

Fix out of bounds error when drawing map circles close to border of the map

---

jsettlers.graphics/src/main/java/jsettlers/graphics/map/draw/MapObjectDrawer.java

Fix missing health indicator for tower occupiers

---

jsettlers.common/src/main/java/jsettlers/common/position/ShortPoint2D.java
jsettlers.common/src/main/java/jsettlers/common/utils/coordinates/CoordinateStream.java
jsettlers.common/src/main/java/jsettlers/common/utils/coordinates/IIntCoordinateFunction.java
jsettlers.logic/src/main/java/jsettlers/algorithms/construction/AbstractConstructionMarkableMap.java
jsettlers.logic/src/main/java/jsettlers/input/GuiInterface.java
jsettlers.logic/src/main/java/jsettlers/input/IGuiInputGrid.java
jsettlers.logic/src/main/java/jsettlers/logic/constants/Constants.java
jsettlers.logic/src/main/java/jsettlers/logic/map/grid/MainGrid.java
jsettlers.logic/src/test/java/jsettlers/algorithms/construction/ConstructionMarksAlgorithmTest.java
jsettlers.main.android/src/main/java/jsettlers/main/android/MainApplication.java
jsettlers.main.android/src/main/java/jsettlers/main/android/core/ui/FragmentUtil.java
jsettlers.main.android/src/main/java/jsettlers/main/android/gameplay/ui/activities/GameActivity.java
jsettlers.main.android/src/main/java/jsettlers/main/android/gameplay/ui/dialogs/PausedDialog.java
jsettlers.main.android/src/main/java/jsettlers/main/android/gameplay/ui/fragments/MapFragment.java
jsettlers.main.android/src/main/java/jsettlers/main/android/gameplay/ui/fragments/menus/settlers/SettlersSoldiersFragment.java
jsettlers.main.android/src/main/res/layout/fragment_map.xml
jsettlers.main.android/src/main/res/menu/game.xml
jsettlers.main.android/src/main/res/values-de/strings.xml
jsettlers.main.android/src/main/res/values/strings.xml

fixes #102.
Changed the way building placement is done to search an area around the selected position for a valid placement position. This area is also larger on mobile to compensate that players don't have a mouse there.

Make it easier to place buildings on mobile

---

jsettlers.main.android/src/main/java/jsettlers/main/android/gameplay/ui/fragments/MapFragment.java

Fix that sometimes the building information tab wasn't shown in the android app.

---

jsettlers.common/src/main/java/jsettlers/common/Color.java
jsettlers.common/src/main/java/jsettlers/common/buildings/loader/BuildingFile.java
jsettlers.common/src/main/java/jsettlers/common/images/OriginalImageLink.java
jsettlers.common/src/main/java/jsettlers/common/utils/OptionableProperties.java
jsettlers.graphics/layoutbuilder/src/main/java/jsettlers/graphics/ui/generate/LayoutConverter.java
jsettlers.graphics/src/main/java/jsettlers/graphics/localization/Labels.java
jsettlers.graphics/src/main/java/jsettlers/graphics/map/draw/ImageProvider.java
jsettlers.logic/src/main/java/jsettlers/logic/map/loading/MapLoader.java
jsettlers.logic/src/main/java/jsettlers/logic/map/loading/list/DirectoryMapLister.java
jsettlers.logic/src/test/java/jsettlers/integration/ai/AiDifficultiesIT.java
jsettlers.main.swing/src/main/java/jsettlers/main/swing/menu/openpanel/OpenPanel.java
jsettlers.mapcreator/src/main/java/jsettlers/exceptionhandler/ExceptionDialog.java
jsettlers.mapcreator/src/main/java/jsettlers/mapcreator/control/EditorControl.java
jsettlers.mapcreator/src/main/java/jsettlers/mapcreator/main/tools/PlaceStackToolbox.java
jsettlers.mapcreator/src/main/java/jsettlers/mapcreator/main/window/OpenPanel.java
jsettlers.mapcreator/src/main/java/jsettlers/mapcreator/mapvalidator/ShowErrorsAction.java
jsettlers.mapcreator/src/main/java/jsettlers/mapcreator/tools/landscape/SetLandscapeTool.java
jsettlers.mapcreator/src/main/java/jsettlers/mapcreator/tools/objects/PlaceBuildingTool.java
jsettlers.mapcreator/src/main/java/jsettlers/mapcreator/tools/objects/PlaceMapObjectTool.java
jsettlers.mapcreator/src/main/java/jsettlers/mapcreator/tools/objects/PlaceMovableTool.java
jsettlers.mapcreator/src/main/java/jsettlers/mapcreator/tools/objects/PlaceStackTool.java
jsettlers.network/src/main/java/jsettlers/network/infrastructure/channel/ping/PingPacketListener.java
jsettlers.network/src/main/java/jsettlers/network/server/match/lockstep/TaskSendingTimerTask.java
jsettlers.network/src/main/java/jsettlers/network/synchronic/timer/NetworkTimer.java
jsettlers.tools/src/main/java/jsettlers/dev/helper/translation/ConvertPropertiesToStandardEncoding.java
jsettlers.tools/src/main/java/jsettlers/graphics/debug/DatFileTester.java
jsettlers.tools/src/main/java/jsettlers/graphics/debug/DataImage.java

Fix usage of String methods with Locale support

---

jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/presenters/picker/NewMultiPlayerPickerPresenter.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/presenters/picker/NewSinglePlayerPickerPresenter.java

Make sure that NewMultiPlayerPickerPresenter correctly unsubscribes from ChangingList events 

---

jsettlers.common/src/main/java/jsettlers/common/menu/IJoinPhaseMultiplayerGameConnector.java
jsettlers.logic/src/main/java/jsettlers/main/MultiplayerGame.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/factories/PresenterFactory.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/presenters/picker/NewMultiPlayerPickerPresenter.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/presenters/picker/NewSinglePlayerPickerPresenter.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/presenters/setup/JoinMultiPlayerSetupPresenterImpl.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/presenters/setup/JoinMultiPlayerSetupPresenterPop.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/presenters/setup/MapSetupPresenter.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/presenters/setup/NewMultiPlayerSetupPresenterImpl.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/presenters/setup/NewMultiPlayerSetupPresenterPop.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/presenters/setup/NewSinglePlayerSetupPresenter.java
jsettlers.main.android/src/main/java/jsettlers/main/android/mainmenu/ui/fragments/setup/MapSetupFragment.java
jsettlers.main.android/src/main/res/values-de/strings.xml
jsettlers.main.android/src/main/res/values/strings.xml

Show toast when user tries to start multiplayer game where not all players are ready

---

jsettlers.main.swing/src/main/java/jsettlers/main/swing/menu/joinpanel/JoinGamePanel.java

 	Fix bug in JoinGamePanel causing joined players to be shown with type AI_VERY_HARD instead of HUMAN

---

jsettlers.tools/src/main/java/jsettlers/graphics/debug/datviewer/DatFileViewer.java

Added drawing of the sequence index in the datfileviewer. Resolves issue #720

Drawing index numbers for sequences

---

go.graphics.swing/src/main/java/go/graphics/swing/contextcreator/BackendSelector.java
go.graphics.swing/src/main/java/go/graphics/swing/contextcreator/WGLContextCreator.java

as instructed by paul on discord

fixed EGL being selectable on Windows
